<html>

<body>
  <p>This page runs Stopify in the browser.</p>
<script src="../../dist/stopify-full.bundle.js"></script>
<script>
var program = `function F() {
    throw new Error('omg');
}

function G() {
  try {
    F();
  }
  catch (exn) {
    throw exn;
  }
}

G();
`;

var runner = stopify.stopifyLocally(program);
runner.g.Error = Error;

runner.run((err) => {
  console.log(err);
  console.log(err.stack.join("\n"));

  // NOTE(arjun): This test case shows that the stack traces are observably
  // different from JavaScript stack traces. In JS, rethrowing an exception
  // will not generate a new stack trace (I think). But, we effectively do
  // so since we clear the stack trace when the program catches.

  // NOTE(arjun): This test case may appear over-specified. But, I believe that
  // for a trivial example like this, we should be able to write the stack
  // trace we want.
  if (err.value.toString().indexOf('omg') >= 0 &&
      err.stack.length === 2 &&
      err.stack[0] === 'Line 10: in G' &&
      err.stack[1] === 'Line 14') {
    window.document.title = 'okay';
  }
  else {
    window.document.title = "error";
  }
});

window.onerror = function() {
  window.document.title = "error";
}
</script>

</body>
</html>